### ISSUE TITLE
加一栏  公司主要使用语言

### ISSUE THREAD

**Issue by tanghaifeng** [tonylee0329/cz_companies#2]
最好再加一栏  公司主要使用语言

**Comment by tonylee0329** [comment]
这个想了下暂时可以先不用加，考虑点:

- 目标群体短期内不想限制到程序员单一工种，希望这个东西可以惠及更多角色
- 技术栈的描述可能并非单一的，比如是要描述后端？前端？对应的，他满足的需求人群也是有限的

**Comment by adadle** [comment]
感谢提议。
这个想了下暂时可以先不用加，考虑点:

- 目标群体短期内不想限制到程序员单一工种，希望这个东西可以惠及更多角色
- 技术栈的描述可能并非单一的，比如是要描述后端？前端？对应的，他满足的需求人群也是有限的
